#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# See dev/README.md for usage, environment variables, and prerequisites.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONTRACTS_DIR="${CONTRACTS_DIR:-$(cd "$REPO_ROOT/../clpr-smart-contracts" && pwd)}"

CLUSTER_NAME="${KIND_CLUSTER:-clpr-dev}"
NAMESPACE="${NAMESPACE:-default}"
MONITORING_NAMESPACE="monitoring"
IMAGE_NAME="clpr-evm-endpoint:dev"
RELEASE_A="relay-a"
RELEASE_B="relay-b"
KPS_RELEASE="kps"
SETUP_ENV="/tmp/clpr-kind-setup.env"

FOUNDRY_IMAGE="ghcr.io/foundry-rs/foundry:latest"
MSG_INTERVAL_MS="${MSG_INTERVAL_MS:-5000}"
MONITORING="${MONITORING:-true}"

# ── Prerequisites ─────────────────────────────────────────────────────────────

for cmd in kind kubectl helm docker; do
    command -v "$cmd" >/dev/null 2>&1 || { echo "ERROR: '$cmd' not found in PATH"; exit 1; }
done

echo "Updating Helm repos..."
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts --force-update
helm repo update prometheus-community

echo "============================================"
echo "  CLPR Kind Dev Setup"
echo "============================================"
echo "Cluster:       $CLUSTER_NAME"
echo "Image:         $IMAGE_NAME"
echo "Contracts dir: $CONTRACTS_DIR"
echo ""

# ── Step 1: Build Docker image ────────────────────────────────────────────────

echo "=== [1/8] Building Docker image ==="
(
    cd "$REPO_ROOT"
    rm -rf clpr-relay-app/build/install/clpr-relay-app
    ./gradlew :clpr-relay-app:installDist -q
    docker build -t "$IMAGE_NAME" .
)
echo "  Built $IMAGE_NAME"

# ── Step 2: Create kind cluster ───────────────────────────────────────────────

echo ""
echo "=== [2/8] Creating kind cluster '$CLUSTER_NAME' ==="

# Generated dynamically so CONTRACTS_DIR and /tmp can be injected as extraMounts.
CLUSTER_CONFIG="$(mktemp /tmp/clpr-kind-cluster-XXXXXX.yaml)"
cat > "$CLUSTER_CONFIG" <<EOF
# Generated by kind-setup.sh — do not edit by hand.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ${CONTRACTS_DIR}
        containerPath: /contracts
        readOnly: true
      - hostPath: /tmp
        containerPath: /host-tmp
    extraPortMappings:
      - containerPort: 30300
        hostPort: 30300
        protocol: TCP
      - containerPort: 30090
        hostPort: 30090
        protocol: TCP
      - containerPort: 30545
        hostPort: 30545
        protocol: TCP
      - containerPort: 30546
        hostPort: 30546
        protocol: TCP
EOF

if kind get clusters 2>/dev/null | grep -qx "$CLUSTER_NAME"; then
    echo "  Cluster already exists — skipping create."
    echo "  NOTE: extraMounts for /contracts and /tmp may not be set on this cluster."
    echo "        If the deployer Job fails, run ./dev/kind-teardown.sh and retry."
else
    kind create cluster --name "$CLUSTER_NAME" --config "$CLUSTER_CONFIG"
fi
rm -f "$CLUSTER_CONFIG"
kubectl config use-context "kind-${CLUSTER_NAME}"

# ── Step 3: Load relay image into kind ────────────────────────────────────────

echo ""
echo "=== [3/8] Loading relay image into kind ==="
kind load docker-image "$IMAGE_NAME" --name "$CLUSTER_NAME"
echo "  $IMAGE_NAME loaded."

# ── Step 4: Install kube-prometheus-stack (shared Grafana + Prometheus) ───────

echo ""
echo "=== [4/8] Installing kube-prometheus-stack ==="
if [[ "$MONITORING" == "true" ]]; then
    kubectl create namespace "$MONITORING_NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
    helm upgrade --install "$KPS_RELEASE" prometheus-community/kube-prometheus-stack \
        --namespace "$MONITORING_NAMESPACE" \
        --values "$REPO_ROOT/dev/values/kube-prometheus-stack.yaml" \
        --wait --timeout=300s
    echo "  Grafana:    http://localhost:30300  (admin / admin)"
    echo "  Prometheus: http://localhost:30090"
else
    echo "  Skipped (MONITORING=false)."
fi

# ── Step 5: Deploy Anvil inside the cluster ───────────────────────────────────

echo ""
echo "=== [5/8] Deploying Anvil ==="

kubectl apply -n "$NAMESPACE" -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anvil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anvil
  template:
    metadata:
      labels:
        app: anvil
    spec:
      containers:
      - name: anvil
        image: ${FOUNDRY_IMAGE}
        imagePullPolicy: IfNotPresent
        command: ["anvil"]
        args:
        - --host=0.0.0.0
        - --chain-id=1337
        - --block-time=1
        - --hardfork=cancun
        - --disable-code-size-limit
        ports:
        - containerPort: 8545
        readinessProbe:
          exec:
            command: ["cast", "block-number", "--rpc-url", "http://localhost:8545"]
          initialDelaySeconds: 3
          periodSeconds: 2
          failureThreshold: 15
---
apiVersion: v1
kind: Service
metadata:
  name: anvil
spec:
  selector:
    app: anvil
  ports:
  - port: 8545
    targetPort: 8545
EOF

echo -n "  Waiting for Anvil to be ready..."
kubectl wait -n "$NAMESPACE" deployment/anvil --for=condition=Available --timeout=120s
echo " ready."

# ── Step 6: Run deployer Job ──────────────────────────────────────────────────

echo ""
echo "=== [6/8] Deploying contracts ==="

kubectl create configmap deploy-scripts \
    -n "$NAMESPACE" \
    --from-file=deploy-contracts.sh="$SCRIPT_DIR/scripts/deploy-contracts.sh" \
    --dry-run=client -o yaml | kubectl apply -f -

# Delete any previous Job before applying — Job specs are immutable.
kubectl delete job deployer -n "$NAMESPACE" --ignore-not-found

kubectl apply -n "$NAMESPACE" -f - <<EOF
apiVersion: batch/v1
kind: Job
metadata:
  name: deployer
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: deployer
        image: ${FOUNDRY_IMAGE}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "/scripts/deploy-contracts.sh"]
        env:
        - name: ANVIL_URL
          value: http://anvil:8545
        - name: CONTRACTS_DIR
          value: /contracts
        - name: RELAY_A_HOST
          value: ${RELEASE_A}-clpr-evm-endpoint-grpc
        - name: RELAY_B_HOST
          value: ${RELEASE_B}-clpr-evm-endpoint-grpc
        # EndpointValidation requires IP literals in updateLedgerConfiguration; the relay
        # reads its peer address from the mock verifier roster (RELAY_{A,B}_HOST above).
        - name: RELAY_A_SEED_IP
          value: "0.0.0.0"
        - name: RELAY_B_SEED_IP
          value: "0.0.0.0"
        - name: OUTPUT_FILE
          value: /host-tmp/clpr-kind-setup.env
        # Redirect forge cache/output away from the read-only contracts mount.
        - name: FOUNDRY_CACHE_PATH
          value: /tmp/forge-cache
        - name: FOUNDRY_OUT
          value: /tmp/forge-out
        volumeMounts:
        - name: contracts
          mountPath: /contracts
          readOnly: true
        - name: scripts
          mountPath: /scripts
        - name: host-tmp
          mountPath: /host-tmp
      volumes:
      - name: contracts
        hostPath:
          path: /contracts
      - name: scripts
        configMap:
          name: deploy-scripts
          defaultMode: 0755
      - name: host-tmp
        hostPath:
          path: /tmp
EOF

echo -n "  Waiting for deployer Job..."
for i in $(seq 1 60); do
    job_status=$(kubectl get job deployer -n "$NAMESPACE" \
        -o jsonpath='{.status.conditions[0].type}' 2>/dev/null || echo "")
    case "$job_status" in
        Complete)
            echo " done."
            break
            ;;
        Failed)
            echo " FAILED"
            echo "  Deployer logs:"
            kubectl logs -n "$NAMESPACE" job/deployer || true
            exit 1
            ;;
    esac
    printf "."
    sleep 5
    if [[ "$i" -eq 60 ]]; then
        echo " TIMEOUT (5m)"
        kubectl logs -n "$NAMESPACE" job/deployer || true
        exit 1
    fi
done

# shellcheck source=/dev/null
source "$SETUP_ENV"
echo "  Contract A:    $CONTRACT_A"
echo "  Contract B:    $CONTRACT_B"
echo "  Mock App A:    $MOCK_APP_A"
echo "  Mock App B:    $MOCK_APP_B"
echo "  Channel ID: $CHANNEL_ID"

# ── Step 7: Deploy relay-a and relay-b ────────────────────────────────────────

echo ""
echo "=== [7/8] Deploying Helm releases ==="

echo "  Waiting for cluster node to be Ready..."
kubectl wait --for=condition=Ready node --all --timeout=120s
echo "  Cluster ready."

SECRET_A="${RELEASE_A}-signing-key"
SECRET_B="${RELEASE_B}-signing-key"

kubectl create secret generic "$SECRET_A" \
    --namespace "$NAMESPACE" \
    --from-literal="signingPrivateKeyHex=${DEV_PRIVATE_KEY_A}" \
    --dry-run=client -o yaml | kubectl apply -f -
echo "  Secret $SECRET_A created/updated."

kubectl create secret generic "$SECRET_B" \
    --namespace "$NAMESPACE" \
    --from-literal="signingPrivateKeyHex=${DEV_PRIVATE_KEY_B}" \
    --dry-run=client -o yaml | kubectl apply -f -
echo "  Secret $SECRET_B created/updated."

if [[ "$MONITORING" == "true" ]]; then
    kubectl create configmap clpr-relay-grafana-dashboard \
        --namespace "$MONITORING_NAMESPACE" \
        --from-file=clpr-relay.json="$REPO_ROOT/dev/dashboards/clpr-relay.json" \
        --dry-run=client -o yaml | kubectl apply -f -
    kubectl label configmap clpr-relay-grafana-dashboard \
        --namespace "$MONITORING_NAMESPACE" \
        grafana_dashboard=1 --overwrite
    echo "  Grafana dashboard ConfigMap applied."
fi

SERVICE_MONITOR="$MONITORING"  # ServiceMonitor requires the Prometheus Operator CRD

helm upgrade --install "$RELEASE_A" "$REPO_ROOT/charts" \
    --namespace "$NAMESPACE" \
    --values "$REPO_ROOT/dev/values/relay.yaml" \
    --set image.registry="" \
    --set image.repository=clpr-evm-endpoint \
    --set image.tag=dev \
    --set image.pullPolicy=Never \
    --set "localNetworks[0].evm.chainId=${CHAIN_ID}" \
    --set "signing.existingSecret=${SECRET_A}" \
    --set "channels[0].channelId=${CHANNEL_ID}" \
    --set "channels[0].commitmentLevel=LATEST" \
    --set "channels[0].localNetwork=local" \
    --set "channels[0].serviceAddress=${CONTRACT_A}" \
    --set "grpc.service.type=ClusterIP" \
    --set "metrics.serviceMonitor.enabled=${SERVICE_MONITOR}" \
    --wait --timeout=300s
echo "  relay-a deployed."

helm upgrade --install "$RELEASE_B" "$REPO_ROOT/charts" \
    --namespace "$NAMESPACE" \
    --values "$REPO_ROOT/dev/values/relay.yaml" \
    --set image.registry="" \
    --set image.repository=clpr-evm-endpoint \
    --set image.tag=dev \
    --set image.pullPolicy=Never \
    --set "localNetworks[0].evm.chainId=${CHAIN_ID}" \
    --set "signing.existingSecret=${SECRET_B}" \
    --set "channels[0].channelId=${CHANNEL_ID}" \
    --set "channels[0].commitmentLevel=LATEST" \
    --set "channels[0].localNetwork=local" \
    --set "channels[0].serviceAddress=${CONTRACT_B}" \
    --set "grpc.service.type=ClusterIP" \
    --set "metrics.serviceMonitor.enabled=${SERVICE_MONITOR}" \
    --wait --timeout=300s
echo "  relay-b deployed."

# ── Step 8: Verify relays, start msg-sender, tail logs ───────────────────────

echo ""
echo "=== [8/8] Verifying relays and starting message sender ==="

relay_ready() {
    local release="$1"
    local local_port="$2"
    local deploy="${release}-clpr-evm-endpoint"
    echo -n "  Waiting for ${release} metrics endpoint..."
    kubectl port-forward -n "$NAMESPACE" "deploy/${deploy}" \
        "${local_port}:9547" >/dev/null 2>&1 &
    local pf_pid=$!
    local ok=0
    for i in $(seq 1 30); do
        sleep 2
        if curl -sf "http://localhost:${local_port}/metrics" >/dev/null 2>&1; then
            ok=1
            break
        fi
    done
    kill "$pf_pid" 2>/dev/null
    wait "$pf_pid" 2>/dev/null || true
    if [ "$ok" -eq 1 ]; then
        echo " ready."
    else
        echo " TIMEOUT — check: kubectl logs -n ${NAMESPACE} deploy/${deploy}"
        exit 1
    fi
}

relay_ready "$RELEASE_A" 19547
relay_ready "$RELEASE_B" 29547

kubectl create configmap send-scripts \
    -n "$NAMESPACE" \
    --from-file=send-messages.sh="$SCRIPT_DIR/scripts/send-messages.sh" \
    --dry-run=client -o yaml | kubectl apply -f -

kubectl create configmap deployed-env \
    -n "$NAMESPACE" \
    --from-file=deployed.env="$SETUP_ENV" \
    --dry-run=client -o yaml | kubectl apply -f -

kubectl apply -n "$NAMESPACE" -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msg-sender
  template:
    metadata:
      labels:
        app: msg-sender
    spec:
      containers:
      - name: sender
        image: ${FOUNDRY_IMAGE}
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "/scripts/send-messages.sh"]
        env:
        - name: ANVIL_URL
          value: http://anvil:8545
        - name: SETUP_ENV
          value: /etc/clpr/deployed.env
        - name: MSG_INTERVAL_MS
          value: "${MSG_INTERVAL_MS}"
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: deployed-env
          mountPath: /etc/clpr
      volumes:
      - name: scripts
        configMap:
          name: send-scripts
          defaultMode: 0755
      - name: deployed-env
        configMap:
          name: deployed-env
EOF

echo "  msg-sender Deployment applied."

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
echo "=== Setup complete ==="
echo ""
echo "  Contract A:    $CONTRACT_A"
echo "  Contract B:    $CONTRACT_B"
echo "  Channel ID: $CHANNEL_ID"
echo ""
if [[ "$MONITORING" == "true" ]]; then
    echo "  Grafana:    http://localhost:30300  (admin / admin)"
    echo "  Prometheus: http://localhost:30090"
    echo ""
fi
echo "  Tail relay-a:  kubectl logs -f -l app.kubernetes.io/instance=${RELEASE_A} -n ${NAMESPACE}"
echo "  Tail relay-b:  kubectl logs -f -l app.kubernetes.io/instance=${RELEASE_B} -n ${NAMESPACE}"
echo "  Both together: kubectl logs -f -l 'app.kubernetes.io/name=clpr-evm-endpoint' -n ${NAMESPACE} --prefix"
echo ""
echo "Tailing both relay logs (Ctrl-C to stop)..."
kubectl logs -f \
    -l "app.kubernetes.io/name=clpr-evm-endpoint" \
    -n "$NAMESPACE" \
    --prefix \
    --max-log-requests 2
