#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Compose deployer entrypoint.
#
# Calls the shared dev/scripts/deploy-contracts.sh (mounted at /deploy-contracts.sh)
# with Compose-appropriate env vars already set by the compose.yaml environment block,
# then generates per-relay YAML config files into the shared volume so relay-a and
# relay-b can pick them up via RELAY_CONFIG_FILE.
#
# The signing key is written into each config's clprServices[].defaultSigningPrivateKeyHex
# (from deployed.env DEV_PRIVATE_KEY_A/B). It can no longer be injected via the
# RELAY_SIGNING_KEY env var: clprServices is a YAML-only list, and a system property cannot
# populate a list element.

set -euo pipefail

# Run the shared deploy script. All required env vars (ANVIL_URL, RELAY_A_HOST,
# RELAY_B_HOST, RELAY_GRPC_PORT, CONTRACTS_DIR, OUTPUT_FILE) are set by compose.yaml.
/bin/bash /deploy-contracts.sh

# Source the addresses and IDs written by deploy-contracts.sh.
# shellcheck disable=SC1091
. "${OUTPUT_FILE}"

SECURE_TRANSPORT="${SECURE_TRANSPORT:-0}"

write_relay_config() {
    local out="$1"
    local contract="$2"
    local name="$3"
    local signing_key="$4"

    # gRPC transport block: the info listener is always plaintext; the sync listener is mandatory mTLS
    # when SECURE_TRANSPORT=1 (CA cert/key mounted at /certs by compose), plaintext otherwise.
    local grpc_block
    if [[ "$SECURE_TRANSPORT" == "1" ]]; then
        grpc_block="  info:
    port: 9546
  sync:
    port: 9545
    tlsEnabled: true
    tlsKeyPath: /certs/${name}-key.der"
    else
        grpc_block="  info:
    port: 9546
  sync:
    port: 9545"
    fi

    cat > "$out" <<EOF
# SPDX-License-Identifier: Apache-2.0
# Generated by Compose deployer — do not edit by hand.
grpc:
  maxMessageSize: 1048576
${grpc_block}

localNetworks:
  - id: local
    proofType: QBFT
    evm:
      jsonRpcUrl: http://anvil:8545
      chainId: 1337
      maxGasPriceCap: "20000000000"
      gasPriorityFee: "1000000000"
      gasBufferMultiplier: 1.2
      pollIntervalMs: 1000

clprServices:
  - serviceAddress: "${contract}"
    localNetwork: local
    defaultSigningPrivateKeyHex: "${signing_key}"
    predefinedChannels:
      - "${CHANNEL_ID}"
EOF
    echo "[deployer] wrote $out"
}

write_relay_config /shared/relay-a.yaml "$CONTRACT_A" relay-a "$DEV_PRIVATE_KEY_A"
write_relay_config /shared/relay-b.yaml "$CONTRACT_B" relay-b "$DEV_PRIVATE_KEY_B"
